-- MySQL Script generated by MySQL Workbench
-- Tue Jul  4 11:46:25 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema dbo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbo` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`movie_actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movie_actors` (
  `movieID` INT(11) NOT NULL,
  `actorID` VARCHAR(45) NOT NULL,
  `actorName` VARCHAR(45) NOT NULL,
  `ranking` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`movie_countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movie_countries` (
  `movie_id` INT(11) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`movie_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`movie_directors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movie_directors` (
  `movieID` INT(11) NOT NULL,
  `directorID` VARCHAR(45) NOT NULL,
  `directorName` VARCHAR(45) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`movie_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movie_genres` (
  `movieid` INT(11) NOT NULL,
  `genre` VARCHAR(45) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`movie_locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movie_locations` (
  `movieID` INT(11) NOT NULL,
  `location1` VARCHAR(200) NULL DEFAULT NULL,
  `location2` VARCHAR(200) NULL DEFAULT NULL,
  `location3` VARCHAR(200) NULL DEFAULT NULL,
  `location4` VARCHAR(200) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`movie_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movie_tags` (
  `movieID` INT(11) NOT NULL,
  `tagID` INT(11) NOT NULL,
  `weight` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movies` (
  `id` INT(11) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `imdbPictureURL` VARCHAR(1000) NULL DEFAULT NULL,
  `year` INT(11) NOT NULL,
  `rtAllCriticsRating` DECIMAL(10,1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tags` (
  `id` INT(11) NOT NULL,
  `value` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`user_taggedmovies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_taggedmovies` (
  `userID` INT(11) NOT NULL,
  `movieID` INT(11) NOT NULL,
  `tagID` INT(11) NOT NULL,
  `date_day` INT(11) NULL DEFAULT NULL,
  `date_month` INT(11) NULL DEFAULT NULL,
  `date_year` INT(11) NULL DEFAULT NULL,
  `date_hour` INT(11) NULL DEFAULT NULL,
  `date_minute` INT(11) NULL DEFAULT NULL,
  `date_second` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
  `idtable1` INT NOT NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;

USE `dbo` ;

-- -----------------------------------------------------
-- Table `dbo`.`Actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`Actors` (
  `ActorID` INT NOT NULL,
  `Name` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`ActorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`Movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`Movies` (
  `MovieID` INT NOT NULL,
  `Rating` DECIMAL(5) NULL,
  `Title` VARCHAR(254) NULL,
  `Photo` VARCHAR(254) NULL,
  `Year` INT NULL,
  `DirectorID` INT NULL,
  `CountryOfProduction` VARCHAR(254) NULL,
  PRIMARY KEY (`MovieID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`Genres` (
  `Genres` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`Genres`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`Directors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`Directors` (
  `DirectorID` INT NOT NULL,
  `Name` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`DirectorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`Countries` (
  `Name` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`Locations` (
  `Region` VARCHAR(254) NOT NULL,
  `City` VARCHAR(254) NOT NULL,
  `Country` VARCHAR(254) NULL,
  PRIMARY KEY (`Region`, `City`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`Tags` (
  `Name` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`Users` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(254) NULL,
  `PasswordHash` VARCHAR(254) NULL,
  `MinRating` DECIMAL(8) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`Starring`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`Starring` (
  `MovieID` INT NOT NULL,
  `ActorID` INT NOT NULL,
  PRIMARY KEY (`MovieID`, `ActorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`FilmedIn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`FilmedIn` (
  `MovieID` INT NOT NULL,
  `Region` VARCHAR(254) NOT NULL,
  `City` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`MovieID`, `Region`, `City`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`FavoriteFilms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`FavoriteFilms` (
  `UserID` INT NOT NULL,
  `MovieID` INT NOT NULL,
  PRIMARY KEY (`UserID`, `MovieID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`FavoriteTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`FavoriteTags` (
  `UserID` INT NOT NULL,
  `TagName` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`UserID`, `TagName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`MovieTaggedAs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`MovieTaggedAs` (
  `MovieID` INT NOT NULL,
  `TagName` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`MovieID`, `TagName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`MovieOfGenre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`MovieOfGenre` (
  `MovieID` INT NOT NULL,
  `GenreName` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`MovieID`, `GenreName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbo`.`FavoriteGenres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbo`.`FavoriteGenres` (
  `UserID` INT NOT NULL,
  `GenreName` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`UserID`, `GenreName`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
